sudo: required

services:
  - docker

script:
   - make DEBIAN_VERSION=lenny
   - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
       docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
       make DEBIAN_VERSION=lenny push ;
     fi
