language: c

sudo: required

services:
  - docker

env:
  matrix:
    - DIST=lenny
    - DIST=etch
    - DIST=squeeze

script:
   - source <(curl https://raw.githubusercontent.com/madworx/cd-ci-glue/master/src/cd-ci-glue.bash) && 
     ( make DEBIAN_VERSION=${DIST} && 
       is_travis_master_push && 
       echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin && 
       make DEBIAN_VERSION=${DIST} push ) || true

jobs:
  include:
    - stage: Publish project description to Docker hub
      env: DIST
      script:
        - curl https://raw.githubusercontent.com/madworx/cd-ci-glue/master/src/cd-ci-glue.bash > cd-ci-glue.bash &&
          source cd-ci-glue.bash && is_travis_master_push && dockerhub_set_description madworx/debian-archive README.md 
